# Generated by Django 6.0.6 on 2026-08-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Momento de la última petición autenticada.', null=True, verbose_name='última actividad'),
        ),
    ]
