# Generated by Django 6.0.6 on 2026-08-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Navegador que tiene la sesión abierta. Vacío = sin sesión.', max_length=64, verbose_name='dispositivo de la sesión'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='descripción del dispositivo'),
        ),
        migrations.AddField(
            model_name='user',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sesión iniciada el'),
        ),
    ]
